### ISSUE TITLE
Criar uma linha com os dados estatísticos diários

### ISSUE THREAD

**Issue by bispojr** [bispojr/observatorio-ufj-covid19#14]

**Comment by bispojr** [comment]
@diegocostacmp ... criei um ramo chamado `feature-14`. Lá estão dois arquivos, um em `_pages` (`teste.html`) e outro no `_includes` (`card_estatisticas.html`). 

Garante a responsividade desta página para as mais diversas resoluções de tela :)

Um abraço,

**Comment by diegocostacmp** [comment]
Boa tarde, como os cards já estão adicionados no projeto estou fechando esta isseu.
